# -*- coding: utf-8 -*-
"""Code3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VKqsXXTffZyNyOl_2NJxugljwtCjvVNi
"""

l=[]
l1=[]
n=int(input("Enter number of customers:"))
for i in range(n):
  l.append(int(input()))
  l1.append(l[i]*2.54)
print(l)
print(l1)