# -*- coding: utf-8 -*-
"""Code1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VKqsXXTffZyNyOl_2NJxugljwtCjvVNi
"""

def fullname(first_name, last_name):
    full_name = first_name + " " + last_name
    return full_name

def string_alternative(full_name):
    return full_name[::2]

def main():
    first_name = input("Enter your first name: ")
    last_name = input("Enter your last name: ")


    full_name = fullname(first_name, last_name)
    print("Full Name:", full_name)


    result = string_alternative(full_name)
    print("Every Other Character in Full Name:", result)

if __name__ == "__main__":
    main()