# -*- coding: utf-8 -*-
"""Code2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VKqsXXTffZyNyOl_2NJxugljwtCjvVNi
"""

text = open("input.txt", "r")
d = dict()
for line in text:

    line = line.strip()
    line = line.lower()
    words = line.split(" ")
    for word in words:
        if word in d:
            d[word] = d[word] + 1
        else:
            d[word] = 1
file1 = open('output.txt', 'w')
s=""
for key in list(d.keys()):
    s+=key+ ":"+ str(d[key])+"\n"
file1.write(s)
file1.close()